### ISSUE TITLE
MX boot options don't save my boot choice!

### ISSUE THREAD

**Issue by onlineapps-cloud** [AdrianTM/mx-boot-options#1]
hi, i created persistent USB drive using MX live USB maker, and all work fine, but i want to boot to `systemd`
![image](https://github.com/user-attachments/assets/9fd1f07b-8ba3-46bd-9aec-bc3d10b9791a)
i tried to configure boot mode using `MX boot options` i selected systemd, click save, reboot, but after reboot, i boot again in to:
![image](https://github.com/user-attachments/assets/7cf0f3c7-803d-49d9-9b3f-d795d4a20542)
If on boot splash screen i type `init=/lib/systemd/systemd` i able to boot in to systemd:
![image](https://github.com/user-attachments/assets/25df3f84-0986-476a-a8a6-a6a82eadfc34)
how to made to always boot in to systemd? i think that MX boot options tool have some issue on this mode
Video demonstration of my actions:

https://github.com/user-attachments/assets/91bc7c2c-9858-48e9-9935-30e91c7abdac

**Comment by onlineapps-cloud** [comment]
USB persistence proof:

https://github.com/user-attachments/assets/e3fb15fe-4472-46e8-957d-da67cbd9b6b2

**Comment by AdrianTM** [comment]
Yeah, unfortunately this Boot Options tools was not designed for the Live environment, it was designed for changing the settings for the installed system, then I extended it to work in Live environment to change the options of the installed system (using chroot) not for setting up the Live environment options -- that was not a priority.

I will have to think how to handle that and actually to understand better how Live environment differs from the installed -- Live environment can actually use 2 ways to boot: GRUB or syslinux, I wonder if you use that "Switch to Grub Bootloader" if it actually works -- I didn't specifically tested in Live but GRUB *might* work. Please let me know...

**Comment by onlineapps-cloud** [comment]
hi, i changed to grub bootloader, press `e`, type boot options, then F10,  and all work fine.
![image](https://github.com/user-attachments/assets/53db137f-0332-475c-ba75-7be349442656)
![image](https://github.com/user-attachments/assets/1192bf52-3f85-42fe-84a0-03890fe1f1e0)

**Comment by AdrianTM** [comment]
Perfect, thanks, so GRUB works, I guess I will have to test for LIve and change syslinux option too.
